apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: naked-to-www-ingress
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      return 301 https://www.duepilot.gr$request_uri;
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: duepilot.gr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummy-service  # must exist, even if never hit
                port:
                  number: 80
  tls:
    - hosts:
        - duepilot.gr
      secretName: www-duepilot-tls