apiVersion: apps/v1
kind: Deployment
metadata:
  name: duepilot-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duepilot-postgres
  template:
    metadata:
      labels:
        app: duepilot-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: duepilot_db
            - name: POSTGRES_USER
              value: duepilot_user
            - name: POSTGRES_PASSWORD
              value: duepilot_pass
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          emptyDir: {}